<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>microservice-framework</artifactId>
        <groupId>uk.gov.justice.services</groupId>
        <version>17.105.0-M7-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>framework-bom</artifactId>
    <packaging>pom</packaging>

    <properties>
        <framework.version>${project.version}</framework.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>uk.gov.justice.framework.libraries</groupId>
                <artifactId>framework-libraries-bom</artifactId>
                <version>${framework-libraries.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>framework-utilities</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>common</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>core</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>messaging-core</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>messaging-jms</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>persistence-deltaspike</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>persistence-jdbc</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>test-utils-core</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>custom</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>jmx-command-handling</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>aggregate</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>test-utils-enveloper-provider</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>test-utils-framework-persistence</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>test-utils-messaging</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>framework-management</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>test-utils-common</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>common-rest</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>event-subscription-test-utils</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>jmx-api</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>event-subscription</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>jmx-command-client</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>test-utils-jmx</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>rest-adapter-file-service</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>rest-adapter-core</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>rest-client-core</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>messaging-client-generator</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>messaging-adapter-core</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>unifiedsearch-core</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>unifiedsearch-client-generator</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.metrics</groupId>
                <artifactId>metrics-servlet</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.metrics</groupId>
                <artifactId>metrics-interceptor</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>framework-healthcheck</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.metrics</groupId>
                <artifactId>metrics-micrometer-core</artifactId>
                <version>${framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>microservices-framework-version</artifactId>
                <version>${framework.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
