<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>microservice-framework</artifactId>
        <groupId>uk.gov.justice.services</groupId>
        <version>25.104.0-M3-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>core</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-core</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-direct-adapter</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>messaging-core</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>messaging-jms</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.schema</groupId>
            <artifactId>schema-service</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.everit-org.json-schema</groupId>
            <artifactId>org.everit.json.schema</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.utils</groupId>
            <artifactId>utilities-core</artifactId>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>uk.gov.justice.utils</groupId>
            <artifactId>test-utils-logging-simple</artifactId>
            <type>pom</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.utils</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-messaging</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava-testlib</artifactId>
            <scope>test</scope>
            <!-- TODO SAN -->
            <!--<exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>-->
        </dependency>
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>jsonassert</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.json</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.parsson</groupId>
            <artifactId>parsson</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path-assert</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomee</groupId>
            <artifactId>openejb-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomee</groupId>
            <artifactId>openejb-server</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomee</groupId>
            <artifactId>openejb-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-common</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>co.unruly</groupId>
            <artifactId>java-8-matchers</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
